# hyprland

$terminal = ghostty
$browser = zen-browser
# $file_man =
# $terminal_file_man =
$menu = wofi --show drun

monitor=,preferred,auto,auto

exec-once = waybar & hypridle & hyprpaper & swaync
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser

$mainMod = SUPER
bind = $mainMod, Q, killactive                             # kill active window
bind = $mainMod, RETURN, exec, $terminal                   # open the terminal
bind = $mainMod, B, exec, $browser                         # open the browser
bind = $mainMod, E, exec, wofi                             # open the filemanager
bind = $mainMod CTRL, R, exec, hyprctl reload              # reload hyprland configuration
bind = $mainMod, L, exec, $lock                            # lock
bind = $mainMod SHIFT, S, exec, $screenshot --now          # screenshot current workspace

bind = $mainMod, 1, workspace, 1  # Open workspace 1
bind = $mainMod, 2, workspace, 2  # Open workspace 2
bind = $mainMod, 3, workspace, 3  # Open workspace 3
# bind = $mainMod, 4, workspace, 4  # Open workspace 4
# bind = $mainMod, 5, workspace, 5  # Open workspace 5
