# config reload
bind r source-file ~/.tmux.conf \; display "  tmux config reloaded."

# prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix



########## SESSIONS ##########

# create session
bind C-c new-session

# split pants using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D




# enable mouse control
set -g mouse on


########## WINDOWS ##########

# don't rename windows automatically
set-option -g allow-rename off




########## DISPLAY ##########

# display ?????
set -g base-index 1
setw -g pane-base-index 1





# bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none





# clock
setw -g clock-mode-colour yellow

# copy
setw -g mode-style 'fg=black bg=red bold'



########## PANES ##########

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'



########## STATUS BAR ##########

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white] #W #[fg=yellow] #F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'





# messages
set -g message-style 'fg=yellow bg=red bold'



##########################################################################################


# prefix
unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# general
set -g default-terminal "screen-256color"
set -g mouse on

# display
set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on

# windows
set-option -g allow-rename off

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# status bar
# set -g status-position bottom

# sessions
bind C-c new-session

# history
set-option -g history-limit 5000

# extras
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

bind x kill-pane
bind X kill-window
bind C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind Q confirm-before -p "kill-session #S? (y/n)" kill

# history
set -g history-limit 5000
