# config reload
bind r source-file ~/.tmux.conf \; display "  tmux config reloaded."

# prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# general
set -g mouse on
set -g history-limit 5000
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
setw -g allow-rename off
setw -g automatic-rename off
setw -g aggressive-resize on
set -g base-index 1
setw -g pane-base-index 1

# key bindings
bind C-c new-session

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind x kill-pane
bind X kill-window
bind C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind Q confirm-before -p "kill-session #S? (y/n)" kill


# appearence & status bar
set -g status-position top
set -g default-terminal "screen-256color"

#setw -g clock-mode-colour yellow

setw -g mode-style 'fg=black bg=red bold'

set -g message-style 'fg=yellow bg=red bold'

set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

#set -g status-justify left
#set -g status-style 'fg=red'

#set -g status-left ''
#set -g status-left-length 10

#set -g status-right-style 'fg=black bg=yellow'
#set -g status-right '%Y-%m-%d %H:%M '
#set -g status-right-length 50

#setw -g window-status-style 'fg=black bg=red'
#setw -g window-status-current-format ' #I #W #F '

#setw -g window-status-style 'fg=red bg=black'
#setw -g window-status-format ' #I #[fg=white] #W #[fg=yellow] #F '

#setw -g window-status-bell-style 'fg=yellow bg=red bold'


# extras
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

